// Voice configuration for the application
// This file centralizes all voice options for better maintainability

export interface VoiceOption {
    id: string;
    name: string;
    provider: string;
    category?: string;
    description?: string;
    language?: string;
    gender?: string;
    age_group?: string;
    accent?: string;
  }
  
  // Hume AI Voices (VoiceCake provider)
  export const humeVoices: VoiceOption[] = [
    // Character Voices
    { id: "Colton Rivers", name: "Colton Rivers", provider: "voicecake", category: "Character", description: "Professional male voice" },
    { id: "Dungeon Master", name: "Dungeon Master", provider: "voicecake", category: "Character", description: "Dramatic fantasy narrator" },
    { id: "Female Meditation Guide", name: "Female Meditation Guide", provider: "voicecake", category: "Wellness", description: "Calming meditation voice" },
    { id: "Friendly Troll", name: "Friendly Troll", provider: "voicecake", category: "Character", description: "Playful fantasy character" },
    { id: "Geraldine Wallace", name: "Geraldine Wallace", provider: "voicecake", category: "Character", description: "Elegant female voice" },
    { id: "Ghost With Unfinished Business", name: "Ghost With Unfinished Business", provider: "voicecake", category: "Character", description: "Mysterious supernatural voice" },
    { id: "Imani Carter", name: "Imani Carter", provider: "voicecake", category: "Character", description: "Warm female voice" },
    { id: "Lady Elizabeth", name: "Lady Elizabeth", provider: "voicecake", category: "Character", description: "Refined British female" },
    { id: "Male Protagonist", name: "Male Protagonist", provider: "voicecake", category: "Character", description: "Heroic male voice" },
    { id: "Medieval Peasant Woman", name: "Medieval Peasant Woman", provider: "voicecake", category: "Character", description: "Historical female voice" },
    { id: "Medieval Town Crier", name: "Medieval Town Crier", provider: "voicecake", category: "Character", description: "Announcing historical voice" },
    { id: "Mrs. Pembroke", name: "Mrs. Pembroke", provider: "voicecake", category: "Character", description: "Sophisticated female voice" },
    { id: "Nasal Podcast Host", name: "Nasal Podcast Host", provider: "voicecake", category: "Media", description: "Casual podcast voice" },
    { id: "Old School Radio Announcer", name: "Old School Radio Announcer", provider: "voicecake", category: "Media", description: "Classic radio voice" },
    { id: "Old-Timey English Priest", name: "Old-Timey English Priest", provider: "voicecake", category: "Character", description: "Historical religious voice" },
    { id: "Pirate Captain", name: "Pirate Captain", provider: "voicecake", category: "Character", description: "Adventurous pirate voice" },
    { id: "Relaxing ASMR Woman", name: "Relaxing ASMR Woman", provider: "voicecake", category: "Wellness", description: "Soothing ASMR voice" },
    { id: "Sad Old British Man", name: "Sad Old British Man", provider: "voicecake", category: "Character", description: "Melancholic British voice" },
    { id: "Scottish Guy", name: "Scottish Guy", provider: "voicecake", category: "Character", description: "Scottish accent male" },
    { id: "Tough Guy", name: "Tough Guy", provider: "voicecake", category: "Character", description: "Strong masculine voice" },
    { id: "Wrestling Announcer", name: "Wrestling Announcer", provider: "voicecake", category: "Media", description: "Energetic sports announcer" },
    { id: "Medieval Peasant Man", name: "Medieval Peasant Man", provider: "voicecake", category: "Character", description: "Historical male voice" },
    { id: "Terrence Bentley", name: "Terrence Bentley", provider: "voicecake", category: "Character", description: "Distinguished male voice" },
    { id: "Sebastian Lockwood", name: "Sebastian Lockwood", provider: "voicecake", category: "Character", description: "Sophisticated British male" },
    { id: "Charming Cowgirl", name: "Charming Cowgirl", provider: "voicecake", category: "Character", description: "Western female voice" },
    { id: "Donovan Sinclair", name: "Donovan Sinclair", provider: "voicecake", category: "Character", description: "Charismatic male voice" },
    { id: "Nature Documentary Narrator", name: "Nature Documentary Narrator", provider: "voicecake", category: "Media", description: "Educational documentary voice" },
    { id: "Alice Bennett", name: "Alice Bennett", provider: "voicecake", category: "Character", description: "Friendly female voice" },
    { id: "Sitcom Girl", name: "Sitcom Girl", provider: "voicecake", category: "Media", description: "Comedic female voice" },
    { id: "Unserious Movie Trailer Narrator", name: "Unserious Movie Trailer Narrator", provider: "voicecake", category: "Media", description: "Funny trailer voice" },
    { id: "Wise Wizard", name: "Wise Wizard", provider: "voicecake", category: "Character", description: "Magical wise voice" },
    { id: "Unserious TV Host", name: "Unserious TV Host", provider: "voicecake", category: "Media", description: "Playful TV host voice" },
    { id: "French Chef", name: "French Chef", provider: "voicecake", category: "Character", description: "French accent chef" },
    { id: "Turtle Guru", name: "Turtle Guru", provider: "voicecake", category: "Character", description: "Wise turtle voice" },
    { id: "Big Dicky", name: "Big Dicky", provider: "voicecake", category: "Character", description: "Bold character voice" },
    { id: "Awe Inspired Guy", name: "Awe Inspired Guy", provider: "voicecake", category: "Character", description: "Inspiring male voice" },
    { id: "Ava Song", name: "Ava Song", provider: "voicecake", category: "Character", description: "Musical female voice" },
    { id: "Sir Spandrel", name: "Sir Spandrel", provider: "voicecake", category: "Character", description: "Noble knight voice" },
    { id: "Live Comedian", name: "Live Comedian", provider: "voicecake", category: "Media", description: "Stand-up comedy voice" },
    { id: "Spanish Instructor", name: "Spanish Instructor", provider: "voicecake", category: "Education", description: "Spanish teaching voice" },
    { id: "Dramatic Movie Trailer Narrator", name: "Dramatic Movie Trailer Narrator", provider: "voicecake", category: "Media", description: "Epic trailer voice" },
    { id: "Vince Douglas", name: "Vince Douglas", provider: "voicecake", category: "Character", description: "Confident male voice" },
    { id: "Campfire Narrator", name: "Campfire Narrator", provider: "voicecake", category: "Character", description: "Storytelling voice" },
    { id: "TikTok Fashion Influencer", name: "TikTok Fashion Influencer", provider: "voicecake", category: "Media", description: "Trendy social media voice" },
    { id: "Male Australian Naturalist", name: "Male Australian Naturalist", provider: "voicecake", category: "Education", description: "Australian nature voice" },
    { id: "English Children's Book Narrator", name: "English Children's Book Narrator", provider: "voicecake", category: "Education", description: "Gentle children's voice" },
    { id: "Literature Professor", name: "Literature Professor", provider: "voicecake", category: "Education", description: "Academic literary voice" },
    { id: "Comforting Male Conversationalist", name: "Comforting Male Conversationalist", provider: "voicecake", category: "Conversational", description: "Warm male conversationalist" },
    { id: "Deep Male Conversational Voice", name: "Deep Male Conversational Voice", provider: "voicecake", category: "Conversational", description: "Rich deep male voice" },
    { id: "Casual Podcast Host", name: "Casual Podcast Host", provider: "voicecake", category: "Media", description: "Relaxed podcast voice" },
    { id: "Cool Journalist", name: "Cool Journalist", provider: "voicecake", category: "Media", description: "Professional journalist voice" },
    { id: "Demure Conversationalist", name: "Demure Conversationalist", provider: "voicecake", category: "Conversational", description: "Gentle female conversationalist" },
    { id: "Conversational English Guy", name: "Conversational English Guy", provider: "voicecake", category: "Conversational", description: "Casual English male" },
    { id: "English Casual Conversationalist", name: "English Casual Conversationalist", provider: "voicecake", category: "Conversational", description: "Relaxed English voice" },
    { id: "Serene Assistant", name: "Serene Assistant", provider: "voicecake", category: "Assistant", description: "Calm AI assistant voice" },
    { id: "Soft Male Conversationalist", name: "Soft Male Conversationalist", provider: "voicecake", category: "Conversational", description: "Gentle male conversationalist" },
    { id: "Booming American Narrator", name: "Booming American Narrator", provider: "voicecake", category: "Media", description: "Powerful American narrator" },
    { id: "Booming British Narrator", name: "Booming British Narrator", provider: "voicecake", category: "Media", description: "Powerful British narrator" },
    { id: "Articulate ASMR British Narrator", name: "Articulate ASMR British Narrator", provider: "voicecake", category: "Wellness", description: "Clear British ASMR voice" },
    { id: "Male English Actor", name: "Male English Actor", provider: "voicecake", category: "Media", description: "Professional English actor" },
    { id: "Cheerful Irishman", name: "Cheerful Irishman", provider: "voicecake", category: "Character", description: "Happy Irish accent" },
    { id: "Friendly Kiwi Guy", name: "Friendly Kiwi Guy", provider: "voicecake", category: "Character", description: "New Zealand male voice" },
    { id: "Friendly Kiwi Girl", name: "Friendly Kiwi Girl", provider: "voicecake", category: "Character", description: "New Zealand female voice" },
    { id: "Highly Reactive Guy", name: "Highly Reactive Guy", provider: "voicecake", category: "Character", description: "Expressive male voice" },
    { id: "Warm Welsh Lady", name: "Warm Welsh Lady", provider: "voicecake", category: "Character", description: "Welsh accent female" },
    { id: "Welsh Folk Storyteller", name: "Welsh Folk Storyteller", provider: "voicecake", category: "Character", description: "Traditional Welsh storyteller" },
    { id: "Cheerful Canadian", name: "Cheerful Canadian", provider: "voicecake", category: "Character", description: "Happy Canadian voice" },
    { id: "Brooding Intellectual Man", name: "Brooding Intellectual Man", provider: "voicecake", category: "Character", description: "Thoughtful intellectual voice" },
    { id: "Groovy Guy", name: "Groovy Guy", provider: "voicecake", category: "Character", description: "Retro cool voice" },
    { id: "Grizzled New Yorker", name: "Grizzled New Yorker", provider: "voicecake", category: "Character", description: "New York accent male" },
    { id: "Opinionated Guy", name: "Opinionated Guy", provider: "voicecake", category: "Character", description: "Strong opinionated voice" },
    { id: "Caring Mother", name: "Caring Mother", provider: "voicecake", category: "Character", description: "Nurturing maternal voice" },
    { id: "Classical Film Actor", name: "Classical Film Actor", provider: "voicecake", category: "Media", description: "Vintage film actor voice" },
    { id: "Inspiring Older Guy", name: "Inspiring Older Guy", provider: "voicecake", category: "Character", description: "Motivational older male" },
    { id: "Inspiring Man", name: "Inspiring Man", provider: "voicecake", category: "Character", description: "Motivational male voice" },
    { id: "Inspiring Woman", name: "Inspiring Woman", provider: "voicecake", category: "Character", description: "Motivational female voice" },
    { id: "Mysterious Woman", name: "Mysterious Woman", provider: "voicecake", category: "Character", description: "Enigmatic female voice" },
    { id: "New York Comedian Guy", name: "New York Comedian Guy", provider: "voicecake", category: "Media", description: "NYC comedy voice" },
    { id: "Expressive Girl", name: "Expressive Girl", provider: "voicecake", category: "Character", description: "Animated female voice" },
    { id: "Charismatic Politician Man", name: "Charismatic Politician Man", provider: "voicecake", category: "Character", description: "Political speaker voice" },
    { id: "Sitcom Guy", name: "Sitcom Guy", provider: "voicecake", category: "Media", description: "Comedic male voice" },
    { id: "Yorkshire Chap", name: "Yorkshire Chap", provider: "voicecake", category: "Character", description: "Yorkshire accent male" },
    { id: "Seasoned Midwestern Actress", name: "Seasoned Midwestern Actress", provider: "voicecake", category: "Media", description: "Midwest American female" },
    { id: "Classical Film Actress", name: "Classical Film Actress", provider: "voicecake", category: "Media", description: "Vintage film actress voice" },
    { id: "Warm American Female", name: "Warm American Female", provider: "voicecake", category: "Character", description: "Friendly American female" },
    { id: "American Lead Actress", name: "American Lead Actress", provider: "voicecake", category: "Media", description: "Professional American actress" },
    { id: "Indian Actor", name: "Indian Actor", provider: "voicecake", category: "Character", description: "Indian accent male" },
    { id: "Indian Actress", name: "Indian Actress", provider: "voicecake", category: "Character", description: "Indian accent female" },
    { id: "California Frat Bro", name: "California Frat Bro", provider: "voicecake", category: "Character", description: "Casual California male" },
    { id: "Comical Vampire", name: "Comical Vampire", provider: "voicecake", category: "Character", description: "Funny vampire voice" },
    { id: "Colorful Fashion Influencer", name: "Colorful Fashion Influencer", provider: "voicecake", category: "Media", description: "Trendy fashion voice" },
    { id: "Excitable British Naturalist", name: "Excitable British Naturalist", provider: "voicecake", category: "Education", description: "Enthusiastic British nature voice" },
    { id: "Aunt Tea", name: "Aunt Tea", provider: "voicecake", category: "Character", description: "Warm aunt voice" },
    { id: "Steve Frisch", name: "Steve Frisch", provider: "voicecake", category: "Character", description: "Friendly male voice" },
    { id: "Warm Female Assistant Voice", name: "Warm Female Assistant Voice", provider: "voicecake", category: "Assistant", description: "Friendly AI assistant" },
    { id: "Male Podcaster", name: "Male Podcaster", provider: "voicecake", category: "Media", description: "Professional male podcaster" },
    { id: "Fastidious Robo-Butler", name: "Fastidious Robo-Butler", provider: "voicecake", category: "Character", description: "Precise robotic butler" },
    { id: "Anna", name: "Anna", provider: "voicecake", category: "Character", description: "Simple female voice" },
    { id: "Leon", name: "Leon", provider: "voicecake", category: "Character", description: "Simple male voice" },
    { id: "Ito", name: "Ito", provider: "voicecake", category: "Character", description: "Simple character voice" },
    { id: "Kora", name: "Kora", provider: "voicecake", category: "Character", description: "Simple character voice" },
    
    // Legacy voices (keeping for backward compatibility)
    // { id: "Lee - Scott", name: "Lee Scott", provider: "voicecake", category: "Legacy", description: "Classic male voice" },
    // { id: "Adele - Young - British", name: "Adele Young British", provider: "voicecake", category: "Legacy", description: "Young British female" },
    // { id: "Steve - American", name: "Steve American", provider: "voicecake", category: "Legacy", description: "American male voice" },
    // { id: "Adam - British", name: "Adam - British", provider: "voicecake", category: "Legacy", description: "British male voice" },
    // { id: "Chloe - British", name: "Chloe British", provider: "voicecake", category: "Legacy", description: "British female voice" },
    // { id: "Veronica - Young - British", name: "Veronica Young British", provider: "voicecake", category: "Legacy", description: "Young British female" },
    // { id: "Lucy - Mature  - British", name: "Lucy Mature British", provider: "voicecake", category: "Legacy", description: "Mature British female" },
    // { id: "Carol  - Mature - British", name: "Carol Mature British", provider: "voicecake", category: "Legacy", description: "Mature British female" },
  ];
  
  // Cartesia voices
  export const cartesiaVoices: VoiceOption[] = [
    // Main voices
    { id: "bf0a246a-8642-498a-9950-80c35e9276b5", name: "Sophie", provider: "cartesia", category: "Main", description: "Sophie voice" },
    { id: "78ab82d5-25be-4f7d-82b3-7ad64e5b85b2", name: "Savannah", provider: "cartesia", category: "Main", description: "Savannah voice" },
    { id: "6f84f4b8-58a2-430c-8c79-688dad597532", name: "Brooke", provider: "cartesia", category: "Main", description: "Brooke voice" },
    { id: "a8a1eb38-5f15-4c1d-8722-7ac0f329727d", name: "Calm French Woman", provider: "cartesia", category: "Character", description: "Calm French accent" },
    { id: "c99d36f3-5ffd-4253-803a-535c1bc9c306", name: "Griffin", provider: "cartesia", category: "Main", description: "Griffin voice" },
    { id: "32b3f3c5-7171-46aa-abe7-b598964aa793", name: "Zia", provider: "cartesia", category: "Main", description: "Zia voice" },
    { id: "79743797-2087-422f-8dc7-86f9efca85f1", name: "Mateo", provider: "cartesia", category: "Main", description: "Mateo voice" },
    { id: "4df027cb-2920-4a1f-8c34-f21529d5c3fe", name: "Carson", provider: "cartesia", category: "Main", description: "Carson voice" },
    { id: "c8605446-247c-4d39-acd4-8f4c28aa363c", name: "Wise Lady", provider: "cartesia", category: "Character", description: "Wise and knowledgeable" },
    { id: "00967b2f-88a6-4a31-8153-110a92134b9f", name: "Ethan", provider: "cartesia", category: "Main", description: "Ethan voice" },
    { id: "afa425cf-5489-4a09-8a3f-d3cb1f82150d", name: "Nico", provider: "cartesia", category: "Main", description: "Nico voice" },
    { id: "1ade29fc-6b82-4607-9e70-361720139b12", name: "Adele", provider: "cartesia", category: "Main", description: "Adele voice" },
    { id: "0c8ed86e-6c64-40f0-b252-b773911de6bb", name: "Corinne", provider: "cartesia", category: "Main", description: "Corinne voice" },
    { id: "f9fc912e-52f0-448a-8bfa-47e9ca75f25a", name: "Marilyn", provider: "cartesia", category: "Main", description: "Marilyn voice" },
    { id: "bbee10a8-4f08-4c5c-8282-e69299115055", name: "Helpful Man", provider: "cartesia", category: "Character", description: "Helpful and friendly" },
    { id: "2747b6cf-fa34-460c-97db-267566918881", name: "Allie", provider: "cartesia", category: "Main", description: "Allie voice" },
    { id: "f9836c6e-a0bd-460e-9d3c-f7299fa60f94", name: "Southern Woman", provider: "cartesia", category: "Character", description: "Southern accent" },
    { id: "f80e7298-93f5-46d0-86f2-b8f29cfc88bd", name: "Welcoming Lady", provider: "cartesia", category: "Character", description: "Warm and welcoming" },
    { id: "57dcab65-68ac-45a6-8480-6c4c52ec1cd1", name: "Kira", provider: "cartesia", category: "Main", description: "Kira voice" },
    { id: "1242fb95-7ddd-44ac-8a05-9e8a22a6137d", name: "Receptionist Woman", provider: "cartesia", category: "Character", description: "Professional receptionist" },
    { id: "f6ff7c0c-e396-40a9-a70b-f7607edb6937", name: "Florence", provider: "cartesia", category: "Main", description: "Florence voice" },
    { id: "f786b574-daa5-4673-aa0c-cbe3e8534c02", name: "Katie", provider: "cartesia", category: "Main", description: "Katie voice" },
    { id: "5c9e800f-2a92-4720-969b-99c4ab8fbc87", name: "Ellen", provider: "cartesia", category: "Main", description: "Ellen voice" },
    { id: "02fe5732-a072-4767-83e3-a91d41d274ca", name: "Madison", provider: "cartesia", category: "Main", description: "Madison voice" },
    { id: "da69d796-4603-4419-8a95-293bfc5679eb", name: "David", provider: "cartesia", category: "Main", description: "David voice" },
    { id: "791d5162-d5eb-40f0-8189-f19db44611d8", name: "Ayush", provider: "cartesia", category: "Main", description: "Ayush voice" },
    { id: "56e35e2d-6eb6-4226-ab8b-9776515a7094", name: "Rupali", provider: "cartesia", category: "Main", description: "Rupali voice" },
    { id: "57c63422-d911-4666-815b-0c332e4d7d6a", name: "Lori", provider: "cartesia", category: "Main", description: "Lori voice" },
    { id: "9fb269e7-70fe-4cbe-aa3f-28bdb67e3e84", name: "Steve", provider: "cartesia", category: "Main", description: "Steve voice" },
    { id: "7b2c0a2e-3dd3-4a44-b16b-26ecd8134279", name: "Luke", provider: "cartesia", category: "Main", description: "Luke voice" },
    { id: "911b8b22-887f-4caf-bf87-85d834c08708", name: "Kenneth", provider: "cartesia", category: "Main", description: "Kenneth voice" },
  
    // Carson emotional variants
    { id: "5c43e078-5ba4-4e1f-9639-8d85a403f76a", name: "Carson Scared", provider: "cartesia", category: "Emotional", description: "Carson scared variant" },
    { id: "3246e36c-ac8c-418d-83cd-4eaad5a3b887", name: "Carson Sad", provider: "cartesia", category: "Emotional", description: "Carson sad variant" },
    { id: "0b32066b-2bcc-44b9-89ab-0223a09d1606", name: "Angry Carson", provider: "cartesia", category: "Emotional", description: "Carson angry variant" },
    { id: "ee8b13e7-98af-4b15-89d1-8d402be10c94", name: "Carson Disgusted", provider: "cartesia", category: "Emotional", description: "Carson disgusted variant" },
    { id: "86e30c1d-714b-4074-a1f2-1cb6b552fb49", name: "Curious Carson", provider: "cartesia", category: "Emotional", description: "Carson curious variant" },
    { id: "96c64eb5-a945-448f-9710-980abe7a514c", name: "Happy Carson", provider: "cartesia", category: "Emotional", description: "Carson happy variant" },
    { id: "66f5935b-af2e-4ec9-bb3e-59112e9ddc93", name: "Carson Surprised", provider: "cartesia", category: "Emotional", description: "Carson surprised variant" },
  
    // Lori emotional variants
    { id: "fb78f09f-f998-4061-ad51-d71f90388f0e", name: "Lori Scared", provider: "cartesia", category: "Emotional", description: "Lori scared variant" },
    { id: "c2da2a3e-b0d6-46bf-a09a-68562617a50a", name: "Lori Surprised", provider: "cartesia", category: "Emotional", description: "Lori surprised variant" },
    { id: "ba0add52-783c-4ec0-8b9c-7a6b60f99d1c", name: "Lori Curious", provider: "cartesia", category: "Emotional", description: "Lori curious variant" },
    { id: "8843adfb-77d3-455a-86f9-de0651555ec6", name: "Lori Happy", provider: "cartesia", category: "Emotional", description: "Lori happy variant" },
    { id: "5cc54223-ec0c-4c50-87e9-b9947264e1f4", name: "Lori Angry", provider: "cartesia", category: "Emotional", description: "Lori angry variant" },
    { id: "414da90b-16b3-4e88-86f5-3c3945e8fa4b", name: "Lori Disgusted", provider: "cartesia", category: "Emotional", description: "Lori disgusted variant" },
    { id: "2d01710c-7c77-4cf1-b0d0-5902a25f6e17", name: "Lori Sad", provider: "cartesia", category: "Emotional", description: "Lori sad variant" },
  
    // Steve emotional variants
    { id: "f96dc0b1-7900-4894-a339-81fb46d515a7", name: "Steve Disgusted", provider: "cartesia", category: "Emotional", description: "Steve disgusted variant" },
    { id: "c1c65fc2-528a-4dde-a2c4-f822785c2704", name: "Steve Curious", provider: "cartesia", category: "Emotional", description: "Steve curious variant" },
    { id: "b1ce5126-4d08-42c3-adef-d3eb39e90c7a", name: "Steve Scared", provider: "cartesia", category: "Emotional", description: "Steve scared variant" },
    { id: "adde00e9-c98f-42ae-a94d-fc9f92f11c76", name: "Steve Happy", provider: "cartesia", category: "Emotional", description: "Steve happy variant" },
    { id: "80713a53-e484-4f69-9852-7891096016ac", name: "Steve Sad", provider: "cartesia", category: "Emotional", description: "Steve sad variant" },
    { id: "7c8ba972-4960-4c43-bea0-8178e2205696", name: "Steve Angry", provider: "cartesia", category: "Emotional", description: "Steve angry variant" },
    { id: "6fd4f468-0345-4f41-81d0-3f48ebc295e0", name: "Steve Surprised", provider: "cartesia", category: "Emotional", description: "Steve surprised variant" },
  
    // David emotional variants
    { id: "fd098a10-ba9e-445e-b144-be2a9f3dac02", name: "David Angry", provider: "cartesia", category: "Emotional", description: "David angry variant" },
    { id: "c4e848dc-d4fd-4bc8-90ea-8525563ec0e5", name: "David Sad", provider: "cartesia", category: "Emotional", description: "David sad variant" },
    { id: "b08c966e-2146-4592-99eb-3171a714a43c", name: "David Curious", provider: "cartesia", category: "Emotional", description: "David curious variant" },
    { id: "a3a4fe2a-d402-41d1-be7d-28f71eda755f", name: "David Scared", provider: "cartesia", category: "Emotional", description: "David scared variant" },
    { id: "9d2b4a7f-7ced-4fb8-b570-9ce21fb931c8", name: "David Disgusted", provider: "cartesia", category: "Emotional", description: "David disgusted variant" },
    { id: "6b622a1d-906f-44af-b60c-7bef365bf124", name: "David Happy", provider: "cartesia", category: "Emotional", description: "David happy variant" },
    { id: "10d17ae0-8f64-472a-be00-f00a98c729e0", name: "David Surprised", provider: "cartesia", category: "Emotional", description: "David surprised variant" },
  
    // Luke emotional variants
    { id: "8e14933d-ecd7-402b-9505-795130d69b35", name: "Luke Curious", provider: "cartesia", category: "Emotional", description: "Luke curious variant" },
    { id: "79b8126f-c5d9-4a73-8585-ba5e1a077ed6", name: "Luke Disgusted", provider: "cartesia", category: "Emotional", description: "Luke disgusted variant" },
    { id: "725d43d6-1196-480e-bd87-728ae5eff9e1", name: "Luke Surprised", provider: "cartesia", category: "Emotional", description: "Luke surprised variant" },
    { id: "63426c82-a0c9-4f23-a175-50eb64c95ec1", name: "Luke Scared", provider: "cartesia", category: "Emotional", description: "Luke scared variant" },
    { id: "61001bc6-9064-40a4-b8b2-29178e0fa558", name: "Luke Angry", provider: "cartesia", category: "Emotional", description: "Luke angry variant" },
    { id: "5c7b66c2-3b58-464d-8a12-093410a269c5", name: "Luke Sad", provider: "cartesia", category: "Emotional", description: "Luke sad variant" },
    { id: "3d79b1fd-daaa-439c-bff3-903dc18e7684", name: "Luke Happy", provider: "cartesia", category: "Emotional", description: "Luke happy variant" },
  
    // Kenneth emotional variants
    { id: "cf14fdcd-24a0-4d63-958a-c784f33d8e7c", name: "Kenneth Curious", provider: "cartesia", category: "Emotional", description: "Kenneth curious variant" },
    { id: "cb605424-d682-48e9-94db-34cc567cf1c6", name: "Kenneth Sad", provider: "cartesia", category: "Emotional", description: "Kenneth sad variant" },
    { id: "abe7dee1-6051-43d3-9a9f-1ac1312497a7", name: "Kenneth Surprised", provider: "cartesia", category: "Emotional", description: "Kenneth surprised variant" },
    { id: "aa086107-101b-4182-a628-c51186d74166", name: "Kenneth Angry", provider: "cartesia", category: "Emotional", description: "Kenneth angry variant" },
    { id: "876c39e1-9ecd-42cd-b0c1-8b3906f0be19", name: "Kenneth Disgusted", provider: "cartesia", category: "Emotional", description: "Kenneth disgusted variant" },
    { id: "83e45f18-fac4-40db-a43b-03257883b437", name: "Kenneth Happy", provider: "cartesia", category: "Emotional", description: "Kenneth happy variant" },
    { id: "64875a07-f57e-4a70-b702-4e3fb25efeda", name: "Kenneth Scared", provider: "cartesia", category: "Emotional", description: "Kenneth scared variant" },
  
    // Madison emotional variants
    { id: "a5def41e-2e73-433f-92f7-5f1d99fef05d", name: "Madison Surprised", provider: "cartesia", category: "Emotional", description: "Madison surprised variant" },
    { id: "98c87826-dba2-44f4-b123-4c7e3c8a2647", name: "Madison Curious", provider: "cartesia", category: "Emotional", description: "Madison curious variant" },
    { id: "62305e79-9d39-4643-b003-5e0b096fe4f4", name: "Madison Happy", provider: "cartesia", category: "Emotional", description: "Madison happy variant" },
    { id: "5993c2c9-5d59-403e-b459-946c8b302086", name: "Madison Disgusted", provider: "cartesia", category: "Emotional", description: "Madison disgusted variant" },
    { id: "30236d07-62d0-4c63-abf7-df46aa45e473", name: "Madison Scared", provider: "cartesia", category: "Emotional", description: "Madison scared variant" },
    { id: "27c12970-3efb-4f39-a78a-2fbb7bddc941", name: "Madison Sad", provider: "cartesia", category: "Emotional", description: "Madison sad variant" },
    { id: "134838f5-ce7e-4876-ac32-6367b99daf83", name: "Madison Angry", provider: "cartesia", category: "Emotional", description: "Madison angry variant" },
  
    // Additional character voices
    { id: "f91ab3e6-5071-4e15-b016-cde6f2bcd222", name: "Aadhya", provider: "cartesia", category: "Character", description: "Aadhya voice" },
    { id: "f31cc6a7-c1e8-4764-980c-60a361443dd1", name: "Olivia", provider: "cartesia", category: "Character", description: "Olivia voice" },
    { id: "04bfd756-4fd4-42c2-9ccf-37f647c5bf54", name: "Samantha Angry", provider: "cartesia", category: "Emotional", description: "Samantha angry variant" },
    { id: "d3e03deb-5439-4203-add1-ca9a7501eaa7", name: "Samantha Yelling", provider: "cartesia", category: "Emotional", description: "Samantha yelling variant" },
    { id: "5e10a334-7fa5-46d4-a64b-5ae6185da3fd", name: "Samantha Sad", provider: "cartesia", category: "Emotional", description: "Samantha sad variant" },
    { id: "761afc95-bef5-44dd-aa07-d3c678912e43", name: "Samantha Happy", provider: "cartesia", category: "Emotional", description: "Samantha happy variant" },
    { id: "d7e54830-4754-4b17-952c-bcdb7e80a2fb", name: "Tori", provider: "cartesia", category: "Character", description: "Tori voice" },
    { id: "4af7c703-f2a9-45dd-a7fd-724cf7efc371", name: "Carrie", provider: "cartesia", category: "Character", description: "Carrie voice" },
    { id: "e8e5fffb-252c-436d-b842-8879b84445b6", name: "Cathy", provider: "cartesia", category: "Character", description: "Cathy voice" },
    { id: "c9440d34-5641-427b-bbb7-80ef7462576d", name: "Joan of Ark", provider: "cartesia", category: "Character", description: "Joan of Ark voice" },
    { id: "55deba52-bc73-4481-ab69-9c8831c8a7c3", name: "Camille", provider: "cartesia", category: "Character", description: "Camille voice" },
    { id: "7a5d4663-88ae-47b7-808e-8f9b9ee4127b", name: "Chen", provider: "cartesia", category: "Character", description: "Chen voice" },
    { id: "c0c374aa-09be-42d9-9828-4d2d7df86962", name: "Isabel", provider: "cartesia", category: "Character", description: "Isabel voice" },
    { id: "146485fd-8736-41c7-88a8-7cdd0da34d84", name: "Chongz", provider: "cartesia", category: "Character", description: "Chongz voice" },
    { id: "9fa83ce3-c3a8-4523-accc-173904582ced", name: "Keith", provider: "cartesia", category: "Character", description: "Keith voice" },
    { id: "5ee9feff-1265-424a-9d7f-8e4d431a12c7", name: "Ronald", provider: "cartesia", category: "Character", description: "Ronald voice" },
    { id: "d718e944-b313-4998-b011-d1cc078d4ef3", name: "Liv", provider: "cartesia", category: "Character", description: "Liv voice" },
    { id: "bfd3644b-d561-4b1c-a01f-d9af98cb67c0", name: "Goofy Matt", provider: "cartesia", category: "Character", description: "Goofy Matt voice" },
    { id: "6a176356-ada1-4b48-b2ae-3a3fdd485680", name: "Night Warden", provider: "cartesia", category: "Character", description: "Night Warden voice" },
    { id: "1fc31370-81b1-4588-9c1a-f93793c6e01d", name: "Luca English", provider: "cartesia", category: "Character", description: "Luca English voice" },
    { id: "e019ed7e-6079-4467-bc7f-b599a5dccf6f", name: "Luca", provider: "cartesia", category: "Character", description: "Luca voice" },
    { id: "bf32f849-7bc9-4b91-8c62-954588efcc30", name: "Chinese Lisa", provider: "cartesia", category: "Character", description: "Chinese Lisa voice" },
    { id: "653b9445-ae0c-4312-a3ce-375504cff31e", name: "Mr. Liu", provider: "cartesia", category: "Character", description: "Mr. Liu voice" },
    { id: "5abd2130-146a-41b1-bcdb-974ea8e19f56", name: "Joan", provider: "cartesia", category: "Character", description: "Joan voice" },
    { id: "8d8ce8c9-44a4-46c4-b10f-9a927b99a853", name: "Connie", provider: "cartesia", category: "Character", description: "Connie voice" },
    { id: "f4e8781b-a420-4080-81cf-576331238efa", name: "Samantha", provider: "cartesia", category: "Character", description: "Samantha voice" },
    { id: "5ef98b2a-68d2-4a35-ac52-632a2d288ea6", name: "Mario", provider: "cartesia", category: "Character", description: "Mario voice" },
    { id: "b042270c-d46f-4d4f-8fb0-7dd7c5fe5615", name: "Juan", provider: "cartesia", category: "Character", description: "Juan voice" },
    { id: "23e9e50a-4ea2-447b-b589-df90dbb848a2", name: "Dallas", provider: "cartesia", category: "Character", description: "Dallas voice" },
    { id: "57b6bf63-c7a1-4ffc-8e10-23bf45152dd6", name: "Rebecca", provider: "cartesia", category: "Character", description: "Rebecca voice" },
    { id: "4f7f1324-1853-48a6-b294-4e78e8036a83", name: "Casper", provider: "cartesia", category: "Character", description: "Casper voice" },
    { id: "ab109683-f31f-40d7-b264-9ec3e26fb85e", name: "Dave", provider: "cartesia", category: "Character", description: "Dave voice" },
    { id: "6adbb439-0865-468c-9e68-adbb0eb2e71c", name: "Sally", provider: "cartesia", category: "Character", description: "Sally voice" },
    { id: "6d287143-8db3-434a-959c-df147192da27", name: "Stacy", provider: "cartesia", category: "Character", description: "Stacy voice" },
    { id: "607167f6-9bf2-473c-accc-ac7b3b66b30b", name: "Brenda", provider: "cartesia", category: "Character", description: "Brenda voice" },
    { id: "87bc56aa-ab01-4baa-9071-77d497064686", name: "Jordan", provider: "cartesia", category: "Character", description: "Jordan voice" },
    { id: "97f4b8fb-f2fe-444b-bb9a-c109783a857a", name: "Nathan", provider: "cartesia", category: "Character", description: "Nathan voice" },
    { id: "729651dc-c6c3-4ee5-97fa-350da1f88600", name: "Pleasant Man", provider: "cartesia", category: "Character", description: "Pleasant Man voice" },
    { id: "794f9389-aac1-45b6-b726-9d9369183238", name: "Sarah Curious", provider: "cartesia", category: "Emotional", description: "Sarah curious variant" },
    { id: "694f9389-aac1-45b6-b726-9d9369183238", name: "Sarah", provider: "cartesia", category: "Character", description: "Sarah voice" },
    { id: "156fb8d2-335b-4950-9cb3-a2d33befec77", name: "Helpful Woman", provider: "cartesia", category: "Character", description: "Helpful Woman voice" },
    { id: "e00d0e4c-a5c8-443f-a8a3-473eb9a62355", name: "Friendly Sidekick", provider: "cartesia", category: "Character", description: "Friendly Sidekick voice" },
    { id: "e13cae5c-ec59-4f71-b0a6-266df3c9bb8e", name: "Madame Mischief", provider: "cartesia", category: "Character", description: "Madame Mischief voice" },
    { id: "7fe6faca-172f-4fd9-a193-25642b8fdb07", name: "American Voiceover Man", provider: "cartesia", category: "Character", description: "American Voiceover Man voice" },
    { id: "2a4d065a-ac91-4203-a015-eb3fc3ee3365", name: "Customer Service Man", provider: "cartesia", category: "Character", description: "Customer Service Man voice" },
    { id: "a8136a0c-9642-497a-882d-8d591bdcb2fa", name: "American Narrator Lady", provider: "cartesia", category: "Character", description: "American Narrator Lady voice" },
    { id: "64462aed-aafc-45d4-84cd-ecb4b3763a0a", name: "American Ad Read Man", provider: "cartesia", category: "Character", description: "American Ad Read Man voice" },
    { id: "39b376fc-488e-4d0c-8b37-e00b72059fdd", name: "Help Desk Man", provider: "cartesia", category: "Character", description: "Help Desk Man voice" },
    { id: "af346552-54bf-4c2b-a4d4-9d2820f51b6c", name: "Help Desk Woman", provider: "cartesia", category: "Character", description: "Help Desk Woman voice" },
    { id: "50d6beb4-80ea-4802-8387-6c948fe84208", name: "The Merchant", provider: "cartesia", category: "Character", description: "The Merchant voice" },
    { id: "34d923aa-c3b5-4f21-aac7-2c1f12730d4b", name: "Griffin Excited", provider: "cartesia", category: "Emotional", description: "Griffin excited variant" },
    { id: "236bb1fb-dc41-4a2b-84d6-d22d2a2aaae1", name: "Old Timey Radio Man", provider: "cartesia", category: "Character", description: "Old Timey Radio Man voice" },
    { id: "ec58877e-44ae-4581-9078-a04225d42bd4", name: "Heroic Man", provider: "cartesia", category: "Character", description: "Heroic Man voice" },
    { id: "d7862948-75c3-4c7c-ae28-2959fe166f49", name: "The Oracle", provider: "cartesia", category: "Character", description: "The Oracle voice" },
    { id: "da4a4eff-3b7e-4846-8f70-f075ff61222c", name: "Australian Salesman", provider: "cartesia", category: "Character", description: "Australian Salesman voice" },
    { id: "8d110413-2f14-44a2-8203-2104db4340e9", name: "Clarion", provider: "cartesia", category: "Character", description: "Clarion voice" },
    { id: "7e19344f-9f17-47d7-a13a-4366ad06ebf3", name: "Silas", provider: "cartesia", category: "Character", description: "Silas voice" },
    { id: "701a96e1-7fdd-4a6c-a81e-a4a450403599", name: "Orion", provider: "cartesia", category: "Character", description: "Orion voice" },
    { id: "cccc21e8-5bcf-4ff0-bc7f-be4e40afc544", name: "Little Gaming Girl", provider: "cartesia", category: "Character", description: "Little Gaming Girl voice" },
    { id: "56b87df1-594d-4135-992c-1112bb504c59", name: "Little Narrator Girl", provider: "cartesia", category: "Character", description: "Little Narrator Girl voice" },
    { id: "7cf0e2b1-8daf-4fe4-89ad-f6039398f359", name: "Benedict", provider: "cartesia", category: "Character", description: "Benedict voice" },
    { id: "586b6832-1ca1-43ad-b974-527dc13c2532", name: "Dorian", provider: "cartesia", category: "Character", description: "Dorian voice" },
    { id: "c2ac25f9-ecc4-4f56-9095-651354df60c0", name: "Commercial Lady", provider: "cartesia", category: "Character", description: "Commercial Lady voice" },
    { id: "d46abd1d-2d02-43e8-819f-51fb652c1c61", name: "Newsman", provider: "cartesia", category: "Character", description: "Newsman voice" },
    { id: "3dcaa773-fb1a-47f7-82a4-1bf756c4e1fb", name: "Harry", provider: "cartesia", category: "Character", description: "Harry voice" },
    { id: "95856005-0332-41b0-935f-352e296aa0df", name: "Classy British Man", provider: "cartesia", category: "Character", description: "Classy British Man voice" },
    { id: "cefcb124-080b-4655-b31f-932f3ee743de", name: "Elena", provider: "cartesia", category: "Character", description: "Elena voice" },
    { id: "e5923af7-a329-4e9b-b95a-5ace4a083535", name: "Lucio", provider: "cartesia", category: "Character", description: "Lucio voice" },
    { id: "38aabb6a-f52b-4fb0-a3d1-988518f4dc06", name: "Alina", provider: "cartesia", category: "Character", description: "Alina voice" },
    { id: "e00dd3df-19e7-4cd4-827a-7ff6687b6954", name: "Lukas", provider: "cartesia", category: "Character", description: "Lukas voice" },
    { id: "87748186-23bb-4158-a1eb-332911b0b708", name: "Wizardman", provider: "cartesia", category: "Character", description: "Wizardman voice" },
    { id: "a167e0f3-df7e-4d52-a9c3-f949145efdab", name: "Customer Support Man", provider: "cartesia", category: "Character", description: "Customer Support Man voice" },
    { id: "41534e16-2966-4c6b-9670-111411def906", name: "1920's Radioman", provider: "cartesia", category: "Character", description: "1920's Radioman voice" },
  
    // Additional international and character voices
    { id: "79f8b5fb-2cc8-479a-80df-29f7a7cf1a3e", name: "Nonfiction Man", provider: "cartesia", category: "Character", description: "Nonfiction Man voice" },
    { id: "00a77add-48d5-4ef6-8157-71e5437b282d", name: "Calm Lady", provider: "cartesia", category: "Character", description: "Calm Lady voice" },
    { id: "f9a4b3a6-b44b-469f-90e3-c8e19bd30e99", name: "Chinese Reading Woman", provider: "cartesia", category: "Character", description: "Chinese Reading Woman voice" },
    { id: "c59c247b-6aa9-4ab6-91f9-9eabea7dc69e", name: "Chinese Lecturer Man", provider: "cartesia", category: "Character", description: "Chinese Lecturer Man voice" },
    { id: "bb2347fe-69e9-4810-873f-ffd759fe8420", name: "Turkish Narrator Lady", provider: "cartesia", category: "Character", description: "Turkish Narrator Lady voice" },
    { id: "d4db5fb9-f44b-4bd1-85fa-192e0f0d75f9", name: "Castilian Spanish Presenter Woman", provider: "cartesia", category: "Character", description: "Castilian Spanish Presenter Woman voice" },
    { id: "b5aa8098-49ef-475d-89b0-c9262ecf33fd", name: "Castilian Spanish Presenter Man", provider: "cartesia", category: "Character", description: "Castilian Spanish Presenter Man voice" },
    { id: "a37639f0-2f0a-4de4-9942-875a187af878", name: "Casual Brazilian Man", provider: "cartesia", category: "Character", description: "Casual Brazilian Man voice" },
    { id: "1cf751f6-8749-43ab-98bd-230dd633abdb", name: "Conversational Brazilian Woman", provider: "cartesia", category: "Character", description: "Conversational Brazilian Woman voice" },
    { id: "304fdbd8-65e6-40d6-ab78-f9d18b9efdf9", name: "Korean Support Woman", provider: "cartesia", category: "Character", description: "Korean Support Woman voice" },
    { id: "af6beeea-d732-40b6-8292-73af0035b740", name: "Korean Narrator Man", provider: "cartesia", category: "Character", description: "Korean Narrator Man voice" },
    { id: "c1cfee3d-532d-47f8-8dd2-8e5b2b66bf1d", name: "Taylan", provider: "cartesia", category: "Character", description: "Taylan voice" },
    { id: "fa7bfcdc-603c-4bf1-a600-a371400d2f8c", name: "Leyla", provider: "cartesia", category: "Character", description: "Leyla voice" },
    { id: "0caedb75-417f-4e36-9b64-c21354cb94c8", name: "Lars", provider: "cartesia", category: "Character", description: "Lars voice" },
    { id: "6c6b05bf-ae5f-4013-82ab-7348e99ffdb2", name: "Freja", provider: "cartesia", category: "Character", description: "Freja voice" },
    { id: "064b17af-d36b-4bfb-b003-be07dba1b649", name: "Tatiana", provider: "cartesia", category: "Character", description: "Tatiana voice" },
    { id: "2a3503b2-b6b6-4534-a224-e8c0679cec4a", name: "Jakub", provider: "cartesia", category: "Character", description: "Jakub voice" },
    { id: "dcf62f33-7cff-4f20-85b2-2efaa68cbc32", name: "Zofia", provider: "cartesia", category: "Character", description: "Zofia voice" },
    { id: "6b92f628-be90-497c-8f4c-3b035002df71", name: "Kenji", provider: "cartesia", category: "Character", description: "Kenji voice" },
    { id: "59d4fd2f-f5eb-4410-8105-58db7661144f", name: "Yuki", provider: "cartesia", category: "Character", description: "Yuki voice" },
    { id: "79693aee-1207-4771-a01e-20c393c89e6f", name: "Marco", provider: "cartesia", category: "Character", description: "Marco voice" },
    { id: "d609f27f-f1a4-410f-85bb-10037b4fba99", name: "Francesca", provider: "cartesia", category: "Character", description: "Francesca voice" },
    { id: "9b953e7b-86a8-42f0-b625-1434fb15392b", name: "Amit", provider: "cartesia", category: "Character", description: "Amit voice" },
    { id: "b7187e84-fe22-4344-ba4a-bc013fcb533e", name: "Sebastian", provider: "cartesia", category: "Character", description: "Sebastian voice" },
    { id: "4ab1ff51-476d-42bb-8019-4d315f7c0c05", name: "Lena", provider: "cartesia", category: "Character", description: "Lena voice" },
    { id: "af482421-80f4-4379-b00c-a118def29cde", name: "Lucas", provider: "cartesia", category: "Character", description: "Lucas voice" },
    { id: "0eb213fe-4658-45bc-9442-33a48b24b133", name: "Sanne", provider: "cartesia", category: "Character", description: "Sanne voice" },
    { id: "6a360542-a117-4ed5-9e09-e8bf9b05eabb", name: "Tiago", provider: "cartesia", category: "Character", description: "Tiago voice" },
    { id: "d4b44b9a-82bc-4b65-b456-763fce4c52f9", name: "Clara", provider: "cartesia", category: "Character", description: "Clara voice" },
    { id: "1d3ba41a-96e6-44ad-aabb-9817c56caa68", name: "Mia", provider: "cartesia", category: "Character", description: "Mia voice" },
    { id: "a38e4e85-e815-43ab-acf1-907c4688dd6c", name: "Grace", provider: "cartesia", category: "Character", description: "Grace voice" },
    { id: "9e7ef2cf-b69c-46ac-9e35-bbfd73ba82af", name: "Ren the Fury", provider: "cartesia", category: "Character", description: "Ren the Fury voice" },
    { id: "c7eafe22-8b71-40cd-850b-c5a3bbd8f8d2", name: "Lily Whisper", provider: "cartesia", category: "Character", description: "Lily Whisper voice" },
    { id: "446f922f-c43a-4aad-9a8b-ad2af568e882", name: "Commanding Japanese Man", provider: "cartesia", category: "Character", description: "Commanding Japanese Man voice" },
    { id: "0cd0cde2-3b93-42b5-bcb9-f214a591aa29", name: "Young Shy Japanese Woman", provider: "cartesia", category: "Character", description: "Young Shy Japanese Woman voice" },
    { id: "a759ecc5-ac21-487e-88c7-288bdfe76999", name: "Intense Japanese Man", provider: "cartesia", category: "Character", description: "Intense Japanese Man voice" },
    { id: "06950fa3-534d-46b3-93bb-f852770ea0b5", name: "Takeshi", provider: "cartesia", category: "Character", description: "Takeshi voice" },
    { id: "da05e96d-ca10-4220-9042-d8acef654fa9", name: "Russian Storyteller Man", provider: "cartesia", category: "Character", description: "Russian Storyteller Man voice" },
    { id: "7ea5e9c2-b719-4dc3-b870-5ba5f14d31d8", name: "Janvi", provider: "cartesia", category: "Character", description: "Janvi voice" },
    { id: "f6141af3-5f94-418c-80ed-a45d450e7e2e", name: "Priya", provider: "cartesia", category: "Character", description: "Priya voice" },
    { id: "f8f5f1b2-f02d-4d8e-a40d-fd850a487b3d", name: "Kiara", provider: "cartesia", category: "Character", description: "Kiara voice" },
    { id: "1259b7e3-cb8a-43df-9446-30971a46b8b0", name: "Devansh", provider: "cartesia", category: "Character", description: "Devansh voice" },
    { id: "9cebb910-d4b7-4a4a-85a4-12c79137724c", name: "Indian Conversational Woman", provider: "cartesia", category: "Character", description: "Indian Conversational Woman voice" },
    { id: "faf0731e-dfb9-4cfc-8119-259a79b27e12", name: "Apoorva", provider: "cartesia", category: "Character", description: "Apoorva voice" },
    { id: "28ca2041-5dda-42df-8123-f58ea9c3da00", name: "Ananya", provider: "cartesia", category: "Character", description: "Ananya voice" },
    { id: "fd2ada67-c2d9-4afe-b474-6386b87d8fc3", name: "Ishan", provider: "cartesia", category: "Character", description: "Ishan voice" },
    { id: "bec003e2-3cb3-429c-8468-206a393c67ad", name: "Parvati", provider: "cartesia", category: "Character", description: "Parvati voice" },
    { id: "be79f378-47fe-4f9c-b92b-f02cefa62ccf", name: "Mihir", provider: "cartesia", category: "Character", description: "Mihir voice" },
    { id: "bdab08ad-4137-4548-b9db-6142854c7525", name: "Hindi Reporter Man", provider: "cartesia", category: "Character", description: "Hindi Reporter Man voice" },
    { id: "9e8db62d-056f-47f3-b3b6-1b05767f9176", name: "Dutch Confident Man", provider: "cartesia", category: "Character", description: "Dutch Confident Man voice" },
    { id: "663afeec-d082-4ab5-827e-2e41bf73a25b", name: "Korean Narrator Woman", provider: "cartesia", category: "Character", description: "Korean Narrator Woman voice" },
    { id: "642014de-c0e3-4133-adc0-36b5309c23e6", name: "Russian Narrator Woman", provider: "cartesia", category: "Character", description: "Russian Narrator Woman voice" },
    { id: "5a31e4fb-f823-4359-aa91-82c0ae9a991c", name: "Turkish Narrator Man", provider: "cartesia", category: "Character", description: "Turkish Narrator Man voice" },
    { id: "575a5d29-1fdc-4d4e-9afa-5a9a71759864", name: "Polish Narrator Woman", provider: "cartesia", category: "Character", description: "Polish Narrator Woman voice" },
    { id: "4ef93bb3-682a-46e6-b881-8e157b6b4388", name: "Polish Narrator Man", provider: "cartesia", category: "Character", description: "Polish Narrator Man voice" },
    { id: "4aa74047-d005-4463-ba2e-a0d9b261fb87", name: "Dutch Man", provider: "cartesia", category: "Character", description: "Dutch Man voice" },
    { id: "408daed0-c597-4c27-aae8-fa0497d644bf", name: "Italian Calm Man", provider: "cartesia", category: "Character", description: "Italian Calm Man voice" },
    { id: "3d335974-4c4a-400a-84dc-ebf4b73aada6", name: "Polish Confident Man", provider: "cartesia", category: "Character", description: "Polish Confident Man voice" },
    { id: "39f753ef-b0eb-41cd-aa53-2f3c284f948f", name: "Turkish Calm Man", provider: "cartesia", category: "Character", description: "Turkish Calm Man voice" },
    { id: "38a146c3-69d7-40ad-aada-76d5a2621758", name: "Swedish Narrator Man", provider: "cartesia", category: "Character", description: "Swedish Narrator Man voice" },
    { id: "2b3bb17d-26b9-421f-b8ca-1dd92332279f", name: "Russian Narrator Man", provider: "cartesia", category: "Character", description: "Russian Narrator Man voice" },
    { id: "29e5f8b4-b953-4160-848f-40fae182235b", name: "Korean Calm Woman", provider: "cartesia", category: "Character", description: "Korean Calm Woman voice" },
    { id: "0e21713a-5e9a-428a-bed4-90d410b87f13", name: "Italian Narrator Woman", provider: "cartesia", category: "Character", description: "Italian Narrator Woman voice" },
    { id: "029c3c7a-b6d9-44f0-814b-200d849830ff", name: "Italian Narrator Man", provider: "cartesia", category: "Character", description: "Italian Narrator Man voice" },
    { id: "421b3369-f63f-4b03-8980-37a44df1d4e8", name: "Friendly Australian Man", provider: "cartesia", category: "Character", description: "Friendly Australian Man voice" },
    { id: "8985388c-1332-4ce7-8d55-789628aa3df4", name: "Australian Narrator Lady", provider: "cartesia", category: "Character", description: "Australian Narrator Lady voice" },
    { id: "41f3c367-e0a8-4a85-89e0-c27bae9c9b6d", name: "Australian Customer Support Man", provider: "cartesia", category: "Character", description: "Australian Customer Support Man voice" },
    { id: "5c5ad5e7-1020-476b-8b91-fdcbe9cc313c", name: "Mexican Woman", provider: "cartesia", category: "Character", description: "Mexican Woman voice" },
    { id: "15d0c2e2-8d29-44c3-be23-d585d5f154a1", name: "Mexican Man", provider: "cartesia", category: "Character", description: "Mexican Man voice" },
    { id: "ee7ea9f8-c0c1-498c-9279-764d6b56d189", name: "Polite Man", provider: "cartesia", category: "Character", description: "Polite Man voice" },
    { id: "b7d50908-b17c-442d-ad8d-810c63997ed9", name: "California Girl", provider: "cartesia", category: "Character", description: "California Girl voice" },
    { id: "b9de4a89-2257-424b-94c2-db18ba68c81a", name: "German Woman", provider: "cartesia", category: "Character", description: "German Woman voice" },
    { id: "6a16c1f4-462b-44de-998d-ccdaa4125a0a", name: "Friendly Brazilian Man", provider: "cartesia", category: "Character", description: "Friendly Brazilian Man voice" },
    { id: "384b625b-da5d-49e8-a76d-a2855d4f31eb", name: "German Conversation Man", provider: "cartesia", category: "Character", description: "German Conversation Man voice" },
    { id: "db229dfe-f5de-4be4-91fd-7b077c158578", name: "German Storyteller Man", provider: "cartesia", category: "Character", description: "German Storyteller Man voice" },
    { id: "0418348a-0ca2-4e90-9986-800fb8b3bbc0", name: "Stern French Man", provider: "cartesia", category: "Character", description: "Stern French Man voice" },
    { id: "5c3c89e5-535f-43ef-b14d-f8ffe148c1f0", name: "French Narrator Man", provider: "cartesia", category: "Character", description: "French Narrator Man voice" },
    { id: "8832a0b5-47b2-4751-bb22-6a8e2149303d", name: "French Narrator Lady", provider: "cartesia", category: "Character", description: "French Narrator Lady voice" },
    { id: "2695b6b5-5543-4be1-96d9-3967fb5e7fec", name: "Spanish-speaking Reporter Man", provider: "cartesia", category: "Character", description: "Spanish-speaking Reporter Man voice" },
    { id: "846fa30b-6e1a-49b9-b7df-6be47092a09a", name: "Spanish Storyteller Man", provider: "cartesia", category: "Character", description: "Spanish Storyteller Man voice" },
    { id: "996a8b96-4804-46f0-8e05-3fd4ef1a87cd", name: "Storyteller Lady", provider: "cartesia", category: "Character", description: "Storyteller Lady voice" },
    { id: "03496517-369a-4db1-8236-3d3ae459ddf7", name: "ASMR Lady", provider: "cartesia", category: "Character", description: "ASMR Lady voice" },
    { id: "bd9120b6-7761-47a6-a446-77ca49132781", name: "Tutorial Man", provider: "cartesia", category: "Character", description: "Tutorial Man voice" },
    { id: "573e3144-a684-4e72-ac2b-9b2063a50b53", name: "Teacher Lady", provider: "cartesia", category: "Character", description: "Teacher Lady voice" },
    { id: "7360f116-6306-4e9a-b487-1235f35a0f21", name: "Commercial Man", provider: "cartesia", category: "Character", description: "Commercial Man voice" },
    { id: "a01c369f-6d2d-4185-bc20-b32c225eab70", name: "British Customer Support Lady", provider: "cartesia", category: "Character", description: "British Customer Support Lady voice" },
    { id: "8f091740-3df1-4795-8bd9-dc62d88e5131", name: "Princess", provider: "cartesia", category: "Character", description: "Princess voice" },
    { id: "043cfc81-d69f-4bee-ae1e-7862cb358650", name: "Australian Woman", provider: "cartesia", category: "Character", description: "Australian Woman voice" },
    { id: "13524ffb-a918-499a-ae97-c98c7c4408c4", name: "Australian Man", provider: "cartesia", category: "Character", description: "Australian Man voice" },
    { id: "829ccd10-f8b3-43cd-b8a0-4aeaa81f3b30", name: "Customer Support Lady", provider: "cartesia", category: "Character", description: "Customer Support Lady voice" },
    { id: "820a3788-2b37-4d21-847a-b65d8a68c99a", name: "Salesman", provider: "cartesia", category: "Character", description: "Salesman voice" },
    { id: "5c42302c-194b-4d0c-ba1a-8cb485c84ab9", name: "Female Nurse", provider: "cartesia", category: "Character", description: "Female Nurse voice" },
    { id: "21b81c14-f85b-436d-aff5-43f2e788ecf8", name: "Laidback Woman", provider: "cartesia", category: "Character", description: "Laidback Woman voice" },
    { id: "726d5ae5-055f-4c3d-8355-d9677de68937", name: "Kentucky Man", provider: "cartesia", category: "Character", description: "Kentucky Man voice" },
    { id: "11af83e2-23eb-452f-956e-7fee218ccb5c", name: "Midwestern Woman", provider: "cartesia", category: "Character", description: "Midwestern Woman voice" },
    { id: "42b39f37-515f-4eee-8546-73e841679c1d", name: "Wise Guide Man", provider: "cartesia", category: "Character", description: "Wise Guide Man voice" },
    { id: "5619d38c-cf51-4d8e-9575-48f61a280413", name: "Announcer Man", provider: "cartesia", category: "Character", description: "Announcer Man voice" },
    { id: "eda5bbff-1ff1-4886-8ef1-4e69a77640a0", name: "Chinese Commercial Man", provider: "cartesia", category: "Character", description: "Chinese Commercial Man voice" },
    { id: "e90c6678-f0d3-4767-9883-5d0ecf5894a8", name: "Chinese Female Conversational", provider: "cartesia", category: "Character", description: "Chinese Female Conversational voice" },
    { id: "d4d4b115-57a0-48ea-9a1a-9898966c2966", name: "Chinese Woman Narrator", provider: "cartesia", category: "Character", description: "Chinese Woman Narrator voice" },
    { id: "ab7c61f5-3daa-47dd-a23b-4ac0aac5f5c3", name: "Friendly French Man", provider: "cartesia", category: "Character", description: "Friendly French Man voice" },
    { id: "700d1ee3-a641-4018-ba6e-899dcadc9e2b", name: "Pleasant Brazilian Lady", provider: "cartesia", category: "Character", description: "Pleasant Brazilian Lady voice" },
    { id: "65b25c5d-ff07-4687-a04c-da2f43ef6fa9", name: "Helpful French Lady", provider: "cartesia", category: "Character", description: "Helpful French Lady voice" },
    { id: "5063f45b-d9e0-4095-b056-8f3ee055d411", name: "Brazilian Young Man", provider: "cartesia", category: "Character", description: "Brazilian Young Man voice" },
    { id: "44863732-e415-4084-8ba1-deabe34ce3d2", name: "Japanese Children Book", provider: "cartesia", category: "Character", description: "Japanese Children Book voice" },
    { id: "3f4ade23-6eb4-4279-ab05-6a144947c4d5", name: "German Conversational Woman", provider: "cartesia", category: "Character", description: "German Conversational Woman voice" },
    { id: "0b904166-a29f-4d2e-bb20-41ca302f98e9", name: "Chinese Commercial Woman", provider: "cartesia", category: "Character", description: "Chinese Commercial Woman voice" },
    { id: "f114a467-c40a-4db8-964d-aaba89cd08fa", name: "Yogaman", provider: "cartesia", category: "Character", description: "Yogaman voice" },
    { id: "a0e99841-438c-4a64-b679-ae501e7d6091", name: "Barbershop Man", provider: "cartesia", category: "Character", description: "Barbershop Man voice" },
    { id: "ed81fd13-2016-4a49-8fe3-c0d2761695fc", name: "Sportsman", provider: "cartesia", category: "Character", description: "Sportsman voice" },
    { id: "c45bc5ec-dc68-4feb-8829-6e6b2748095d", name: "Movieman", provider: "cartesia", category: "Character", description: "Movieman voice" },
    { id: "bf991597-6c13-47e4-8411-91ec2de5c466", name: "Newslady", provider: "cartesia", category: "Character", description: "Newslady voice" },
    { id: "248be419-c632-4f23-adf1-5324ed7dbf1d", name: "Professional Woman", provider: "cartesia", category: "Character", description: "Professional Woman voice" },
    { id: "63ff761f-c1e8-414b-b969-d1833d1c870c", name: "Confident British Man", provider: "cartesia", category: "Character", description: "Confident British Man voice" },
    { id: "98a34ef2-2140-4c28-9c71-663dc4dd7022", name: "Southern Man", provider: "cartesia", category: "Character", description: "Southern Man voice" },
    { id: "3b554273-4299-48b9-9aaf-eefd438e3941", name: "Indian Lady", provider: "cartesia", category: "Character", description: "Indian Lady voice" },
    { id: "36b42fcb-60c5-4bec-b077-cb1a00a92ec6", name: "Pilot over Intercom", provider: "cartesia", category: "Character", description: "Pilot over Intercom voice" },
    { id: "daf747c6-6bc2-4083-bd59-aa94dce23f5d", name: "Middle Eastern Woman", provider: "cartesia", category: "Character", description: "Middle Eastern Woman voice" },
    { id: "e3827ec5-697a-4b7c-9704-1a23041bbc51", name: "Sweet Lady", provider: "cartesia", category: "Character", description: "Sweet Lady voice" },
    { id: "638efaaa-4d0c-442e-b701-3fae16aad012", name: "Indian Man", provider: "cartesia", category: "Character", description: "Indian Man voice" },
    { id: "2b568345-1d48-4047-b25f-7baccf842eb0", name: "Japanese Woman Conversational", provider: "cartesia", category: "Character", description: "Japanese Woman Conversational voice" },
    { id: "15a9cd88-84b0-4a8b-95f2-5d583b54c72e", name: "Reading Lady", provider: "cartesia", category: "Character", description: "Reading Lady voice" },
    { id: "565510e8-6b45-45de-8758-13588fbaec73", name: "Midwestern Man", provider: "cartesia", category: "Character", description: "Midwestern Man voice" },
    { id: "40104aff-a015-4da1-9912-af950fbec99e", name: "Alabama Man", provider: "cartesia", category: "Character", description: "Alabama Man voice" },
    { id: "34575e71-908f-4ab6-ab54-b08c95d6597d", name: "New York Man", provider: "cartesia", category: "Character", description: "New York Man voice" },
    { id: "fb26447f-308b-471e-8b00-8e9f04284eb5", name: "Doctor Mischief", provider: "cartesia", category: "Character", description: "Doctor Mischief voice" },
    { id: "71a7ad14-091c-4e8e-a314-022ece01c121", name: "British Reading Lady", provider: "cartesia", category: "Character", description: "British Reading Lady voice" },
    { id: "e8a863c6-22c7-4671-86ca-91cacffc038d", name: "Japanese Male Conversational", provider: "cartesia", category: "Character", description: "Japanese Male Conversational voice" },
    { id: "91b4cf29-5166-44eb-8054-30d40ecc8081", name: "Anna", provider: "cartesia", category: "Character", description: "Anna voice" },
    { id: "779673f3-895f-4935-b6b5-b031dc78b319", name: "Russian Calm Woman", provider: "cartesia", category: "Character", description: "Russian Calm Woman voice" },
    { id: "95d51f79-c397-46f9-b49a-23763d3eaa2d", name: "Hinglish Speaking Woman", provider: "cartesia", category: "Character", description: "Hinglish Speaking Woman voice" },
    { id: "82a7fc13-2927-4e42-9b8a-bb1f9e506521", name: "Polish Young Man", provider: "cartesia", category: "Character", description: "Polish Young Man voice" },
    { id: "f852eb8d-a177-48cd-bf63-7e4dcab61a36", name: "Swedish Calm Lady", provider: "cartesia", category: "Character", description: "Swedish Calm Lady voice" },
    { id: "97e7d7a9-dfaa-4758-a936-f5f844ac34cc", name: "Japanese Narration Man", provider: "cartesia", category: "Character", description: "Japanese Narration Man voice" },
    { id: "7f423809-0011-4658-ba48-a411f5e516ba", name: "Hindi Narrator Man", provider: "cartesia", category: "Character", description: "Hindi Narrator Man voice" },
    { id: "11c61307-4f9e-4db8-ac3b-bfa5f2a731ce", name: "Sabine", provider: "cartesia", category: "Character", description: "Sabine voice" },
    { id: "9626c31c-bec5-4cca-baa8-f8ba9e84c8bc", name: "Jacqueline", provider: "cartesia", category: "Character", description: "Jacqueline voice" },
  ];
  
  // All voices combined
  export const allVoices: VoiceOption[] = [
    ...humeVoices,
    ...cartesiaVoices,
  ];
  
  // Get voices by provider
  export const getVoicesByProvider = (provider: string): VoiceOption[] => {
    return allVoices.filter(voice => voice.provider === provider);
  };
  
  // Get voices by category
  export const getVoicesByCategory = (provider: string, category?: string): VoiceOption[] => {
    const providerVoices = getVoicesByProvider(provider);
    if (!category) return providerVoices;
    return providerVoices.filter(voice => voice.category === category);
  };
  
  // Get unique categories for a provider
  export const getCategoriesByProvider = (provider: string): string[] => {
    const providerVoices = getVoicesByProvider(provider);
    const categories = providerVoices
      .map(voice => voice.category)
      .filter((category): category is string => category !== undefined);
    return [...new Set(categories)];
  };
  
  // Search voices by name or description
  export const searchVoices = (provider: string, searchTerm: string): VoiceOption[] => {
    const providerVoices = getVoicesByProvider(provider);
    const term = searchTerm.toLowerCase();
    return providerVoices.filter(voice => 
      voice.name.toLowerCase().includes(term) ||
      voice.description?.toLowerCase().includes(term) ||
      voice.category?.toLowerCase().includes(term)
    );
  };
  